### ISSUE TITLE
Moving docs to https://testing-library.com/bucklescript?

### ISSUE THREAD

**Issue by kentcdodds** [wyze/bs-dom-testing-library#5]
Hey @wyze! Would you be interested in moving your docs to https://testing-library.com/bucklescript? (Similar to https://testing-library.com/react and https://testing-library.com/cypress)

The site source is here: https://github.com/alexkrolick/testing-library-docs

I think it'd be pretty trivial to move things over.

What do you think? cc @alexkrolick

**Comment by wyze** [comment]
I had family in town this week, so sorry for the delayed response. I'm definitely on board with consolidating the documentation. I can see if I can get a PR over there this week to get it added!

**Comment by kentcdodds** [comment]
Super!

**Comment by wyze** [comment]
I finally got around to this and opened my PR this morning https://github.com/alexkrolick/testing-library-docs/pull/29. Once it gets merged I'll update the readme here with a link over to it and we can close this issue out!
